### ISSUE TITLE
Incorrect balance is shown

### ISSUE THREAD

**Issue by DaMarkov** [runplay/run-wallet-android#1]
The balance of an address and therefore the total balance of a wallet is not calculated correctly.

How to reproduce:

Created a new wallet with two addresses a1, a2.
I received 107i on address a1 (transaction is confirmed).
Send 50i from a1 to a2. The app will spend all 107i of a1 send 50i to address a2 and the remainder of 57i to address a2.
After confirmation a2 has a balance of 50i according to the app.

Expected behaviour:

The remainder address should not be same as the receiving address.
In any case, after the second transaction a balance of 107i for a2 should be displayed.

**Comment by pcooperuk** [comment]
Will look into, does not sound right... could be possibly that the app wanted an a3 address... but regardless the a2 should be showing the full balance.
Will look into...

**Comment by DaMarkov** [comment]
How is the balance of an address calculated? For example for address BILISTFUPRCMDEDHUXVJRGEOTKVHXFBCITOKKPDJIZWNHTEAEVVFHGWRNTKYLPGUMOSYCVWDKSKJZDLID the app shows a balance of 0 under the "receive" tap.
If I click on the address I see two transfers one with +107i and another with -50i (which is correct).

I propose that the balance of an address should be determined by calling getBalances(). (This should also work better if a snapshot happens)

**Comment by runplay** [comment]
closed with update #37f73da
