### ISSUE TITLE
Promote (nudge) does not promote a transaction, but reattaches the transfer

### ISSUE THREAD

**Issue by DaMarkov** [runplay/run-wallet-android#2]
When promoting a bundle the app reattaches the bundle to the tangle instead of creating a new transaction which validates the initial bundle.

**Comment by pcooperuk** [comment]
Hi, yes the re-broadcast should in the next release, the app is badly worded.  The (same) feature will actually be re-broadcasting a few times before doing a full nudge (re-attach)

**Comment by runplay** [comment]
closed with update #37f73da
