### ISSUE TITLE
Piggy bank address gets broken after receiving IOTA

### ISSUE THREAD

**Issue by DaMarkov** [runplay/run-wallet-android#3]
Sorry to bother you again (by the way huge thanks for the recent update!)

How to reproduce:

1. Make an address a piggy bank address.
2. Receive IOTA to that address.
3. After the transaction is confirmed, the address is no longer a piggy bank address.

Expected behaviour:

The address should remain a piggy bank address after the transaction is confirmed.
I think the app marks the receiving addresses of a transaction automatically as piggy bank addresses, which interferes when the user sets a piggy bank address manually.

**Comment by pcooperuk** [comment]
Thanks and correct, should remain a pig, will look into.
big update coming  around 13/14th Feb will ensure fixed in that.

**Comment by runplay** [comment]
Thanks, yes correct should remain a pig.
Big update coming around 13/14 Feb, will ensure it works correct in that.

**Comment by runplay** [comment]
fixed in #b91acc9
