### ISSUE TITLE
Password Lock

### ISSUE THREAD

**Issue by Emryzz** [runplay/run-wallet-android#4]
Hey man, there seems to be a bug with the password-lock of the app. After setting up a Passwort and closing the App, the app prompts for an password on reopening - but there is only an PIN input interface, nothing for a string. Also, an Option to deactivate Password Protection would be nice.

Reproduction:

Go into Security Settings
Create Password as string
save and close the app
reopen app.

thanks, and kudos! great app

**Comment by runplay** [comment]
Thanks for the Report, just saw on Google Play as well (thank for the nice stars too).

Does sound odd, all the password fields should only allow Number input, not sure how you even got to enter A-Z characters, if possible could you send a screenshot with the keyboard open to iota@runplay.com ? or attach here if can.  Will help, but at the moment sounds like a device specific issue (are you using a non-standard android keyboard?)

btw, just updated, now has 10 different colour themes :) - updating Google Play soon
Oh also, yes wallet re-naming will be in the next update (should have been there already)

**Comment by Emryzz** [comment]
Hey man - yes you're right. I used the keepass2 keyboard for security reasons, and created a password there, then just copied it. 
So to be correct: I did not create a string password in the app but externally, and pasted it there. 

The input field looked like a string input, that's why I was confused. 

So maybe you could use a keypad input field where pasting is not possible. (Or let the usr choose a string additionally)

Thanks for your feedback and the update! Will check it out later!

**Comment by runplay** [comment]
Thanks, can look into allowing characters as well as number, just standardised that way, mainly for simplicity.
