### ISSUE TITLE
URI scheme

### ISSUE THREAD

**Issue by joakim** [runplay/run-wallet-android#6]
I noticed your wallet has a URI scheme for deep links – nice!

It's identical to [the scheme I've proposed](https://github.com/joakim/iota-uri-scheme), except for the double slashes (`iota://`) instead of `iota:`, which is semantically more correct (to be nerdy).

I have an explanation in my feedback to Eric Hop's deep link proposal (halfway down):
https://github.com/joakim/iota-uri-scheme/issues/2

Just wanted to give you a quick feedback, and a heads up on my proposal. Without giving too much away, there is some momentum for the version without double slashes, but only time will tell what ends up becoming the standard. Anyway, feedback to my proposal would be greatly appreciated!

**Comment by runplay** [comment]
Hi,

Please don't suggest deep linking like that, it's wrong and it wont work in practice
I have had this discussion on IOTA discord already, you can read about valid deep linking here:
http://mobiledeeplinking.org/
https://developer.android.com/training/app-links/deep-linking.html

I also wrote this
https://medium.com/@runplay/http-is-not-deep-linking-use-it-do-not-use-it-and-why-ac0e2fb7123c

As some of the testers of the Trinity app seemed to think http://somedomain.com?address=....
deep linking was the way to go, it's not either.

As a side note, it should be iota://  not even iota:/
I only included the single trail version as it might possibly work and I saw in IOTA discord someone mentioning this as well (naturally want to be compatible with Trinity), so to anticipate this i implemented that as well as a just in case.

Your version of iota:addres.... 
Simply will not work in Android and very doubtful in IOS, windows, linux systems.

It should follow protocol://address
http://www.google.com
udp://www.google.com
iota://address?


edit...
I stand corrected, I can get iota:address to work...
but it still stands, follow the standard that everyone else uses.
If Trinity does implement iota:address not iota://address the the run wallet will support it, but run wallet wont be listing it as the way as it's more important to do it the way that everyone else does.

**Comment by joakim** [comment]
First, I agree that HTTP(S) deep links is not the solution for IOTA, with many different wallets on different operating systems. It should have a widely adopted and supported URI scheme for interoperability.

Then I supppose we disagree on what exactly _the standard_ is. I followed IETF's [STD66](https://tools.ietf.org/html/std66), also explained [here](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax). There's no authority (host/ip) in a DAG, so `//` would actually go against the standard.

Yes, many apps still use `//`. And it's strictly not even necessary. I don't know why developers went with that, maybe it _feels_ more solid, more established, almost as if it could be a real protocol? Or maybe support for URI schemes without `//` were not as good some years ago?

But there are quite a few apps that do follow STD66. Some examples from [IANA's list](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml):
- Google Talk (`gtalk:chat?jid=<jid>`)
- Spotify (`spotify:track:<track>`)
- Skype (`skype:<username>`)
- Magnet links (`magnet:?xt=urn:sha1:<hash of file>&dn=<display name>`)
- Bitcoin (`bitcoin:<address>`)

And there's of course the familiar `mailto:<email address>` and `tel:<phone number>` schemes.

I'd find it strange if all these big apps and systems wouldn't work on the most commonly used operating systems..

That said, I don't know what type of scheme works _best_ on for example iOS and Android, as I've never had to implement a scheme on those platforms. But you confirm that `iota:` does work on Android, and I suspect it will work on iOS too.

**Comment by runplay** [comment]
Good talking with you on the discord chat i will be making compatible with your method, but do bear in mind, this is an app on Google Android only.  With that I will leave this link:

Open this in Google Chrome on  Google Android
http://www.runplay.com/deeplinks.html
The page has 2 links, one your way, one the Google recommended way. 1 works, 1 does not.

Both links are designed to open run IOTA wallet in Google Play.
so for a Google OS, to open in Google Play using Google Chrome browser and deep link to run IOTA wallet.
probably worth noting this is the same link that you would use to open one app within another app using Android Intenets.

Will close this now.
https://developer.android.com/distribute/marketing-tools/linking-to-google-play.html

**Comment by joakim** [comment]
Yes, that example is true for the Play Store. Google has apparently chosen only to support `market://`, and they do seem to prefer double slash URIs in Android (`content://` for example). But that's not proof that the same is true for all URI schemes. Whether they would pass a test like that depends on their definition and how they're supported by apps.

For example, you could try these URIs on Android (if you have apps that support them):
spotify:track:47Uol4fhspIMlVoCavLaaD
skype:joakimstai
bitcoin:19aedHZsyT3cS3VpV8bVd5pNiTR9b6K5XY

You'll notice that some of them will support URIs with or without double slash, even though they're defined and generally used without slashes. I don't see any harm in that, at least not for IOTA (there are no slashes in IOTA addresses).

Android of course also has support for the widely used `mailto:`, `tel:`, `sms:`, `mms:`, `geo:` and probably some more schemes that don't use slashes. Those are actually good examples of URIs without an "authority" (a host/server/IP address), which is also the case for IOTA. These URI schemes adhere to the STD66 and therefore don't use `//`, and my opinion is that IOTA should do the same.

To drive the point home, [Sir Tim Berners-Lee has only one regret...](https://bits.blogs.nytimes.com/2009/10/12/the-webs-inventor-regrets-one-small-thing/) :)

You're free to do whatever you want with your app though, and I think it's a good idea to support both variants regardless of what ends up being the norm.

Thanks for the discussion!
