### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by glupeksha** [runplay/run-wallet-android#7]
Error:(140, 44) No resource found that matches the given name (at 'drawableRight' with value '@drawable/print').

**Comment by runplay** [comment]
This should not happen anymore when doing

$ git clone https://github.com/runplay/run-wallet-android
$ cd run-wallet-android
$ ./gradlew clean build

Will close this, if you still have any problems, can you contact iota@runplay.com or raise a new issue again with the Error, also if possible a complete copy of the build trace
